main: ${groupId}.${artifactId}.${name}
name: ${name}
version: ${version}
description: ${description}
authors: [Rayzr]
#depend: [PerceiveCore]
#commands:
#  ${artifactId}:
#    description: ${name} main command
#    aliases: [alias1,alias2]
#    usage: "/${artifactId} [command]"
#    permission: ${name}.main
